settings:

    log_mode: text
    output_mode: cli
    
    update_interval: 15
    start_worker_interval: 15
    market_data_chunk_size: 25
 
    market_pairs:
        - BTC/USDT
        - 1INCH/USDT
        - AAVE/USDT
        - ADA/USDT
        - AION/USDT
        - AKRO/USDT
        - ALGO/USDT
        - ALICE/USDT
        - ALPACA/USDT
        - ALPHA/USDT
        - ANKR/USDT
        - ANT/USDT
        - ARDR/USDT
        - ARPA/USDT
        - AR/USDT
        - ATA/USDT
        - ATOM/USDT
        - AUDIO/USDT
        - AVA/USDT
        - AVAX/USDT
        - AXS/USDT
        - BADGER/USDT
        - BAKE/USDT
        - BAL/USDT
        - BAND/USDT
        - BAT/USDT
        - BCH/USDT
        - BEAM/USDT
        - BEL/USDT
        - BLZ/USDT
        - BNT/USDT
        - BOND/USDT
        - BTCST/USDT
        - BTT/USDT
        - BURGER/USDT
        - C98/USDT
        - CAKE/USDT
        - CELO/USDT
        - CELR/USDT
        - CFX/USDT
        - CHR/USDT
        - CHZ/USDT
        - CKB/USDT
        - CLV/USDT
        - COCOS/USDT
        - COMP/USDT
        - COS/USDT
        - COTI/USDT
        - CRV/USDT
        - CTK/USDT
        - CTSI/USDT
        - CTXC/USDT
        - CVC/USDT
        - DASH/USDT
        - DATA/USDT
        - DCR/USDT
        - DEGO/USDT
        - DENT/USDT
        - DGB/USDT
        - DIA/USDT
        - DNT/USDT
        - DOCK/USDT
        - DODO/USDT
        - DOGE/USDT
        - DOT/USDT
        - DUSK/USDT
        - EGLD/USDT
        - ENJ/USDT
        - EOS/USDT
        - EPS/USDT
        - ERN/USDT
        - ETC/USDT
        - FARM/USDT
        - FET/USDT
        - FIL/USDT
        - FIO/USDT
        - FIRO/USDT
        - FLM/USDT
        - FLOW/USDT
        - FORTH/USDT
        - FTM/USDT
        - FTT/USDT
        - FUN/USDT
        - GRT/USDT
        - GTC/USDT
        - GXS/USDT
        - HARD/USDT
        - HBAR/USDT
        - HIVE/USDT
        - HNT/USDT
        - HOT/USDT
        - ICP/USDT
        - ICX/USDT
        - INJ/USDT
        - IOST/USDT
        - IOTA/USDT
        - IOTX/USDT
        - IRIS/USDT
        - JST/USDT
        - KAVA/USDT
        - KEEP/USDT
        - KEY/USDT
        - KLAY/USDT
        - KMD/USDT
        - KNC/USDT
        - KSM/USDT
        - LINA/USDT
        - LINK/USDT
        - LIT/USDT
        - LPT/USDT
        - LRC/USDT
        - LSK/USDT
        - LTC/USDT
        - LTO/USDT
        - LUNA/USDT
        - MANA/USDT
        - MASK/USDT
        - MATIC/USDT
        - MBL/USDT
        - MDT/USDT
        - MDX/USDT
        - MFT/USDT
        - MINA/USDT
        - MITH/USDT
        - MKR/USDT
        - MLN/USDT
        - MTL/USDT
        - NANO/USDT
        - NEAR/USDT
        - NEO/USDT
        - NMR/USDT
        - NULS/USDT
        - NU/USDT
        - OCEAN/USDT
        - OGN/USDT
        - OMG/USDT
        - OM/USDT
        - ONE/USDT
        - ONG/USDT
        - ONT/USDT
        - ORN/USDT
        - OXT/USDT
        - PAXG/USDT
        - PERP/USDT
        - PHA/USDT
        - POLS/USDT
        - POND/USDT
        - PSG/USDT
        - PUNDIX/USDT
        - QNT/USDT
        - QTUM/USDT
        - QUICK/USDT
        - RAMP/USDT
        - RAY/USDT
        - REEF/USDT
        - REP/USDT
        - RIF/USDT
        - RLC/USDT
        - ROSE/USDT
        - RSR/USDT
        - RUNE/USDT
        - RVN/USDT
        - SAND/USDT
        - SC/USDT
        - SFP/USDT
        - SHIB/USDT
        - SKL/USDT
        - SLP/USDT
        - SNX/USDT
        - SOL/USDT
        - SRM/USDT
        - STMX/USDT
        - STORJ/USDT
        - STPT/USDT
        - STRAX/USDT
        - STX/USDT
        - SUN/USDT
        - SUPER/USDT
        - SUSHI/USDT
        - SXP/USDT
        - TFUEL/USDT
        - THETA/USDT
        - TKO/USDT
        - TLM/USDT
        - TOMO/USDT
        - TRB/USDT
        - TROY/USDT
        - TRU/USDT
        - TRX/USDT
        - TVK/USDT
        - TWT/USDT
        - UMA/USDT
        - UNI/USDT
        - UTK/USDT
        - VET/USDT
        - VTHO/USDT
        - WAN/USDT
        - WAVES/USDT
        - WIN/USDT
        - WNXM/USDT
        - WRX/USDT
        - WTC/USDT
        - XEM/USDT
        - XLM/USDT
        - XMR/USDT
        - XRP/USDT
        - XTZ/USDT
        - XVG/USDT
        - XVS/USDT
        - YFII/USDT
        - YFI/USDT
        - ZEC/USDT
        - ZEN/USDT
        - ZIL/USDT
        - ZRX/USDT
        - BNB/USDT
        - ETH/USDT
        - REN/USDT
        - NKN/USDT
        - BTS/USDT
        - BTG/USDT
        - MIR/USDT
        - MBOX/USDT
        - FOR/USDT
        - REQ/USDT
        - GHST/USDT
        - WAXP/USDT
        - GNO/USDT
        - XEC/USDT
        - ELF/USDT
        - DYDX/USDT
        - POLY/USDT
        - IDEX/USDT
        - GALA/USDT
        - ILV/USDT
        - YGG/USDT
        - SYS/USDT
        - FIDA/USDT
        - FRONT/USDT
        - CVP/USDT
        - AGLD/USDT
        - RAD/USDT
        - BETA/USDT
        - RARE/USDT
        - CHESS/USDT
        - ADX/USDT
        - AUCTION/USDT
        - DAR/USDT
        - BNX/USDT
        - RGT/USDT
        - MOVR/USDT
        - ENS/USDT
        - KP3R/USDT
        - POWR/USDT
        - VGX/USDT
        - JASMY/USDT
        - AMP/USDT
        - PLA/USDT
        - PYR/USDT
        - RNDR/USDT
        - ALCX/USDT
        - MC/USDT
        - ANY/USDT
        - BICO/USDT
        - FLUX/USDT
        - FXS/USDT
        - VOXEL/USDT
        - CVX/USDT
        - SPELL/USDT
        - JOE/USDT


exchanges:
    binance:
        required:
            enabled: true
        # all_pairs:
        #   - USDT
        exclude: 
          - USDC
          - PAX
          - BUSD 
          - 1GOLD
          - ALUSD
          - BGBP
          - BITCNY
          - BITEUR
          - BITGOLD
          - BITUSD
          - BKRW
          - BRCP
          - BVND
          - CEUR
          - COFFIN
          - CONST
          - CUSD
          - DGD
          - DGX
          - DPT
          - DUSD
          - EBASE
          - EOSDT
          - EURS
          - EURT
          - FLUSD
          - FRAX
          - GUSD
          - HGT
          - HUSD
          - IDRT
          - ITL
          - KBC
          - LUSD
          - MDO
          - MDS
          - MIM
          - MTR
          - MUSD
          - OUSD
          - PAR
          - QC
          - RSV
          - SBD
          - SUSD
          - TRIBE
          - TRYB
          - UETH
          - USDB
          - USDEX
          - USDFL
          - USDK
          - USDL
          - USDP
          - USDQ
          - USDS
          - USDX
          - USNBT
          - UST
          - VAI
          - XAUR
          - XCHF
          - XEUR
          - XIDR
          - XSGD
          - XUSD
          - ZUSD

indicators:
    iiv:
        - enabled: true
          alert_enabled: true
          alert_frequency: always
          signal:
            - iiv
          # hot: 5
          hot: 300
          cold: 0
          candle_period: 5m
          # period_count: 2

informants:
 
    ohlcv:
        - enabled: true
          signal:
            # - high
            # - low
            - close
          candle_period: 5m
          period_count: 1
    sma:
        - enabled: false

notifiers:
    webhook:
      required:
        url: http://192.168.100.7:5000/webhook
      optional:
        username: null
        password: null
